INSERT INTO public.lessons (position, title_fr, title_en, intro_fr, intro_en, takeaway_fr, takeaway_en) VALUES
(1,'Le message de la Bible','The Message of the Bible','La Bible n''est pas un livre ordinaire : elle raconte l''histoire d''un Dieu qui parle. Prenons le temps d''écouter ce qu''elle dit d''elle-même.','The Bible is no ordinary book: it tells the story of a God who speaks. Let''s take time to hear what it says about itself.','La Bible se présente comme la parole de Dieu, donnée pour éclairer et transformer la vie.','The Bible presents itself as God''s word, given to enlighten and transform life.'),
(2,'Le monde et son destin','The World and Its Destiny','Où va notre monde ? La Bible répond par une prophétie donnée à un roi de Babylone, il y a plus de 2 500 ans.','Where is our world heading? The Bible answers through a prophecy given to a king of Babylon more than 2,500 years ago.','L''histoire humaine n''est pas un hasard : elle avance vers le royaume éternel de Dieu.','Human history is not random: it moves toward God''s eternal kingdom.'),
(3,'Vers un monde nouveau','Toward a New World','Dieu ne se contente pas de réparer : il promet une création entièrement renouvelée.','God does not merely repair: he promises an entirely renewed creation.','La promesse finale de la Bible est un monde sans larmes, où Dieu habite avec les siens.','The Bible''s final promise is a world without tears, where God dwells with his people.'),
(4,'Le retour du Christ','The Return of Christ','L''espérance du retour de Jésus traverse toute l''Écriture. Découvrons ce que Jésus lui-même a promis.','The hope of Jesus'' return runs through all of Scripture. Let''s discover what Jesus himself promised.','Le retour de Jésus n''est pas un événement secret, mais une manifestation glorieuse et visible par tous.','Jesus'' return is not a secret event, but a glorious manifestation visible to all.'),
(5,'Les signes des temps','The Signs of the Times','Jésus a donné des repères pour que ses disciples ne soient pas surpris : non des sujets de peur, mais d''attente confiante.','Jesus gave signposts so his disciples would not be caught unaware: not reasons for fear, but for confident expectation.','Les signes invitent à la vigilance sereine, non à l''angoisse ni aux calculs de dates.','The signs invite calm watchfulness, not anxiety or date-setting.'),
(6,'Dieu existe','God Exists','Avant de parler de doctrines, arrêtons-nous sur une question simple : qui est ce Dieu que la Bible nous présente ?','Before speaking of doctrines, let''s pause on a simple question: who is this God the Bible presents?','Le Dieu de la Bible est créateur, personnel, et son caractère se résume en un mot : amour.','The God of the Bible is creator, personal, and his character is summed up in one word: love.'),
(7,'Satan','Satan','Le mal n''a pas toujours existé. La Bible en explique l''origine avec sobriété.','Evil has not always existed. The Bible explains its origin soberly.','Satan est un être vaincu par la croix ; son pouvoir est réel mais limité et temporaire.','Satan is a being defeated by the cross; his power is real but limited and temporary.'),
(8,'Jésus-Christ','Jesus Christ','Au centre de la Bible se tient une personne. Découvrons qui est Jésus et pourquoi il est venu.','At the centre of the Bible stands a person. Let''s discover who Jesus is and why he came.','Jésus est pleinement Dieu et pleinement homme : il connaît notre faiblesse et il peut sauver.','Jesus is fully God and fully human: he knows our weakness and he can save.'),
(9,'Le péché','Sin','Le mot « péché » peut sembler dur. La Bible l''emploie pourtant avec tendresse : elle nomme le mal pour pouvoir le guérir.','The word "sin" can sound harsh. Yet the Bible uses it tenderly: it names the illness in order to heal it.','Le péché est une rupture de relation ; le remède n''est pas l''effort, mais la grâce.','Sin is a broken relationship; the remedy is not effort, but grace.'),
(10,'La conversion','Conversion','La conversion n''est pas un effort de perfection : c''est un retournement du cœur vers celui qui nous aime.','Conversion is not an effort at perfection: it is a turning of the heart toward the one who loves us.','Se convertir, c''est accepter d''être aimé et de laisser Dieu conduire.','To be converted is to accept being loved and to let God lead.'),
(11,'La nouvelle naissance','The New Birth','Jésus parle d''un commencement radicalement nouveau, offert à chacun, quel que soit son passé.','Jesus speaks of a radically new beginning, offered to everyone, whatever their past.','La nouvelle naissance est l''œuvre de l''Esprit, pas un exploit humain.','The new birth is the Spirit''s work, not a human achievement.'),
(12,'La Loi de Dieu','The Law of God','La loi de Dieu n''est pas un fardeau : c''est le portrait de son caractère et une protection pour la vie.','God''s law is not a burden: it is the portrait of his character and a protection for life.','La loi révèle l''amour ; la grâce donne la force de le vivre.','The law reveals love; grace gives the strength to live it.'),
(13,'Le septième jour','The Seventh Day','Au cœur de la semaine, Dieu a placé un jour de repos. Voyons son origine et son sens.','At the heart of the week God placed a day of rest. Let''s look at its origin and meaning.','Le sabbat est un cadeau : un temps béni pour respirer avec Dieu.','The Sabbath is a gift: a blessed time to breathe with God.'),
(14,'Le dimanche','Sunday','Comment le premier jour de la semaine a-t-il pris tant d''importance ? Regardons ce que dit l''Écriture, sans polémique.','How did the first day of the week become so important? Let''s look at what Scripture says, without polemics.','L''Écriture reste notre repère quand la coutume et le commandement divergent.','Scripture remains our reference when custom and commandment diverge.'),
(15,'La prière','Prayer','Prier, c''est simplement parler avec un Père qui écoute. Aucun vocabulaire particulier n''est requis.','To pray is simply to speak with a Father who listens. No special vocabulary is required.','La prière est une relation, pas une performance.','Prayer is a relationship, not a performance.'),
(16,'La mort','Death','Ce sujet touche chacun de nous. La Bible en parle avec réalisme et avec une espérance étonnante.','This subject touches each of us. The Bible speaks of it realistically and with a surprising hope.','La mort est un sommeil dont Jésus vient réveiller les siens.','Death is a sleep from which Jesus comes to wake his own.'),
(17,'L''enfer','Hell','Beaucoup d''images populaires ne viennent pas de la Bible. Lisons les textes eux-mêmes.','Many popular images do not come from the Bible. Let''s read the texts themselves.','Dieu est juste et il ne se réjouit pas de la souffrance : le mal aura une fin.','God is just and takes no delight in suffering: evil will have an end.'),
(18,'Le millénium','The Millennium','Mille ans mentionnés dans l''Apocalypse : que se passe-t-il durant cette période, et où ?','A thousand years mentioned in Revelation: what happens during that period, and where?','Le millénium est un temps de jugement transparent, où toutes les questions reçoivent réponse.','The millennium is a time of transparent judgment, when every question receives an answer.'),
(19,'Le jugement','The Judgment','Le jugement de Dieu n''est pas une menace pour celui qui a confiance : c''est la garantie que la justice existe.','God''s judgment is not a threat for the one who trusts: it is the guarantee that justice exists.','Le juge est aussi l''avocat : Jésus se tient de notre côté.','The judge is also the advocate: Jesus stands on our side.'),
(20,'La véritable Église','The True Church','Comment reconnaître une communauté fidèle à Jésus ? L''Apocalypse donne des repères simples.','How can we recognise a community faithful to Jesus? Revelation gives simple markers.','L''Église n''est pas parfaite, mais elle est reconnaissable à sa fidélité à Jésus et à sa Parole.','The church is not perfect, but it is recognisable by its faithfulness to Jesus and his Word.'),
(21,'Le baptême','Baptism','Le baptême est une réponse d''amour, jamais une contrainte. Voyons son sens dans le Nouveau Testament.','Baptism is a response of love, never a constraint. Let''s see its meaning in the New Testament.','Le baptême exprime publiquement une décision intérieure déjà prise avec Jésus.','Baptism publicly expresses an inner decision already made with Jesus.'),
(22,'La libéralité','Stewardship and Generosity','Tout ce que nous avons est reçu. La générosité est la joie de rendre une part à celui qui donne tout.','Everything we have is received. Generosity is the joy of returning a share to the one who gives everything.','Donner n''appauvrit pas : cela libère le cœur.','Giving does not impoverish: it frees the heart.'),
(23,'La santé','Health','Le corps n''est pas séparé de la vie spirituelle. Dieu s''intéresse à notre bien-être entier.','The body is not separate from spiritual life. God cares about our whole well-being.','Prendre soin de son corps fait partie de la reconnaissance envers le Créateur.','Caring for the body is part of gratitude toward the Creator.'),
(24,'Sur les traces de Jésus','Following in Jesus'' Footsteps','Suivre Jésus, c''est marcher avec lui au quotidien : dans le service, le pardon et la confiance.','Following Jesus means walking with him daily: in service, forgiveness and trust.','La vie chrétienne est un chemin partagé, pas une performance solitaire.','The Christian life is a shared path, not a solitary performance.'),
(25,'Résumé des leçons 23 et 24','Summary of Lessons 23 and 24','Une relecture paisible de ce que nous avons découvert sur la santé et sur la marche avec Jésus.','A peaceful review of what we discovered about health and about walking with Jesus.','Revenir sur le chemin parcouru aide à avancer avec assurance.','Looking back over the road travelled helps us move forward with assurance.');

INSERT INTO public.lesson_questions (lesson_id, position, verse_ref, prompt_fr, prompt_en)
SELECT l.id, v.qpos, v.ref, v.fr, v.en
FROM (VALUES
(1,1,'2 Timothée 3:16-17','Quelle est l''origine de l''Écriture, et à quoi est-elle utile ?','What is the origin of Scripture, and what is it useful for?'),
(1,2,'2 Pierre 1:20-21','Comment les prophètes ont-ils reçu leur message ?','How did the prophets receive their message?'),
(1,3,'Psaume 119:105','À quoi la parole de Dieu est-elle comparée ?','What is God''s word compared to?'),
(1,4,'Jean 17:17','Que dit Jésus au sujet de la parole du Père ?','What does Jesus say about the Father''s word?'),
(2,1,'Daniel 2:31-35','Décrivez la statue vue par Nebucadnetsar.','Describe the statue Nebuchadnezzar saw.'),
(2,2,'Daniel 2:37-40','Quels royaumes sont représentés par les différents métaux ?','Which kingdoms are represented by the different metals?'),
(2,3,'Daniel 2:44','Quel royaume viendra après tous les autres ?','Which kingdom will come after all the others?'),
(2,4,'Daniel 2:45','Pourquoi cette prophétie est-elle digne de confiance ?','Why can this prophecy be trusted?'),
(3,1,'Ésaïe 65:17','Que Dieu annonce-t-il qu''il va créer ?','What does God announce he will create?'),
(3,2,'Apocalypse 21:1-4','Qu''est-ce qui disparaîtra dans le monde nouveau ?','What will disappear in the new world?'),
(3,3,'Ésaïe 35:5-6','Quels changements sont promis pour les corps humains ?','What changes are promised for human bodies?'),
(3,4,'2 Pierre 3:13','Quelle attitude le croyant adopte-t-il face à cette promesse ?','What attitude does the believer take toward this promise?'),
(4,1,'Jean 14:1-3','Quelle promesse Jésus a-t-il faite à ses disciples avant son départ ?','What promise did Jesus make to his disciples before he left?'),
(4,2,'Actes 1:9-11','Comment le Christ reviendra-t-il, selon les anges ?','How will Christ return, according to the angels?'),
(4,3,'Matthieu 24:27','Ce retour sera-t-il discret ou visible ?','Will this return be quiet or visible?'),
(4,4,'1 Thessaloniciens 4:16-17','Que se passera-t-il pour les croyants à ce moment-là ?','What will happen to believers at that moment?'),
(5,1,'Matthieu 24:6-7','Quels bouleversements Jésus annonce-t-il ?','What upheavals does Jesus announce?'),
(5,2,'2 Timothée 3:1-5','Quels traits marqueront la société des derniers jours ?','What traits will mark the society of the last days?'),
(5,3,'Matthieu 24:14','Quel signe positif est donné avant la fin ?','What positive sign is given before the end?'),
(5,4,'Matthieu 24:36','Que dit Jésus sur le jour et l''heure ?','What does Jesus say about the day and the hour?'),
(6,1,'Psaume 19:1-2','Que révèle la création au sujet de Dieu ?','What does creation reveal about God?'),
(6,2,'Romains 1:19-20','Pourquoi Paul dit-il que Dieu est reconnaissable ?','Why does Paul say God can be recognised?'),
(6,3,'1 Jean 4:8','Comment Jean définit-il Dieu ?','How does John define God?'),
(6,4,'Jérémie 29:13','Quelle promesse est faite à celui qui cherche Dieu ?','What promise is given to the one who seeks God?'),
(7,1,'Ézéchiel 28:14-15','Comment cet être était-il au commencement ?','What was this being like in the beginning?'),
(7,2,'Ésaïe 14:12-14','Quelle attitude a provoqué sa chute ?','What attitude caused his fall?'),
(7,3,'Apocalypse 12:7-9','Que s''est-il passé dans le ciel ?','What happened in heaven?'),
(7,4,'Jacques 4:7','Quelle est la réponse du croyant face à la tentation ?','What is the believer''s response to temptation?'),
(8,1,'Jean 1:1-3','Qui est la Parole, et qu''a-t-elle fait ?','Who is the Word, and what did the Word do?'),
(8,2,'Ésaïe 53:4-5','Que porte le Serviteur souffrant à notre place ?','What does the Suffering Servant bear in our place?'),
(8,3,'Hébreux 4:15','Pourquoi Jésus peut-il comprendre nos épreuves ?','Why can Jesus understand our struggles?'),
(8,4,'Jean 3:16','Quelle est la motivation première de Dieu ?','What is God''s primary motivation?'),
(9,1,'1 Jean 3:4','Comment la Bible définit-elle le péché ?','How does the Bible define sin?'),
(9,2,'Romains 3:23','Qui est concerné par cette réalité ?','Who is affected by this reality?'),
(9,3,'Ésaïe 59:2','Quelle est la conséquence du péché dans la relation avec Dieu ?','What is sin''s consequence for our relationship with God?'),
(9,4,'1 Jean 1:9','Que promet Dieu à celui qui confesse ?','What does God promise to the one who confesses?'),
(10,1,'Actes 3:19','Quelles deux actions sont associées à la conversion ?','What two actions are linked with conversion?'),
(10,2,'Ézéchiel 36:26','Que Dieu promet-il de changer en nous ?','What does God promise to change in us?'),
(10,3,'Luc 15:20','Comment le père accueille-t-il le fils qui revient ?','How does the father welcome the returning son?'),
(10,4,'Apocalypse 3:20','Comment Jésus se présente-t-il à la porte du cœur ?','How does Jesus present himself at the heart''s door?'),
(11,1,'Jean 3:3-5','Que faut-il pour voir le royaume de Dieu ?','What is needed to see the kingdom of God?'),
(11,2,'2 Corinthiens 5:17','Que devient celui qui est en Christ ?','What becomes of the one who is in Christ?'),
(11,3,'Galates 2:20','Comment Paul décrit-il sa nouvelle vie ?','How does Paul describe his new life?'),
(11,4,'Tite 3:5','Sur quoi repose le salut ?','On what does salvation rest?'),
(12,1,'Exode 20:3-17','Quels sont les dix commandements ?','What are the ten commandments?'),
(12,2,'Matthieu 22:37-40','Comment Jésus résume-t-il la loi ?','How does Jesus summarise the law?'),
(12,3,'Matthieu 5:17','Jésus est-il venu abolir la loi ?','Did Jesus come to abolish the law?'),
(12,4,'Romains 3:31','Quel lien Paul fait-il entre la foi et la loi ?','What link does Paul make between faith and the law?'),
(13,1,'Genèse 2:2-3','Qu''a fait Dieu le septième jour ?','What did God do on the seventh day?'),
(13,2,'Exode 20:8-11','Que demande le quatrième commandement ?','What does the fourth commandment ask?'),
(13,3,'Luc 4:16','Quelle était l''habitude de Jésus ce jour-là ?','What was Jesus'' habit on that day?'),
(13,4,'Marc 2:27-28','Pour qui le sabbat a-t-il été fait ?','For whom was the Sabbath made?'),
(14,1,'Marc 16:9','Quel événement s''est produit le premier jour de la semaine ?','What event took place on the first day of the week?'),
(14,2,'Actes 20:7','Que faisaient les disciples réunis ce jour-là ?','What were the disciples doing gathered that day?'),
(14,3,'Daniel 7:25','Quel changement une puissance devait-elle tenter ?','What change would a power attempt?'),
(14,4,'Actes 5:29','Quel principe guide le croyant en cas de conflit ?','What principle guides the believer in case of conflict?'),
(15,1,'Matthieu 6:6-9','Quels conseils Jésus donne-t-il sur la prière ?','What advice does Jesus give about prayer?'),
(15,2,'Philippiens 4:6-7','Que reçoit celui qui confie ses soucis à Dieu ?','What does the one who entrusts worries to God receive?'),
(15,3,'1 Jean 5:14-15','Quelle assurance avons-nous en priant ?','What assurance do we have in praying?'),
(15,4,'Luc 18:1','Quelle est la leçon de la parabole ?','What is the lesson of the parable?'),
(16,1,'Genèse 2:7','De quoi l''être humain est-il composé ?','What is the human being made of?'),
(16,2,'Ecclésiaste 9:5-6','Quelle est la condition des morts ?','What is the condition of the dead?'),
(16,3,'Jean 11:11-14','Quel mot Jésus emploie-t-il pour la mort ?','What word does Jesus use for death?'),
(16,4,'1 Thessaloniciens 4:16','Quand les morts en Christ se lèveront-ils ?','When will the dead in Christ rise?'),
(17,1,'Malachie 4:1','Que deviennent les méchants selon ce verset ?','What becomes of the wicked according to this verse?'),
(17,2,'Apocalypse 20:9','D''où vient le feu, et quand agit-il ?','Where does the fire come from, and when does it act?'),
(17,3,'Romains 6:23','Quel est le salaire du péché ?','What is the wage of sin?'),
(17,4,'Ézéchiel 33:11','Quel est le désir de Dieu pour le pécheur ?','What is God''s desire for the sinner?'),
(18,1,'Apocalypse 20:1-3','Que devient Satan pendant mille ans ?','What becomes of Satan during the thousand years?'),
(18,2,'Apocalypse 20:4','Que font les rachetés durant cette période ?','What do the redeemed do during this period?'),
(18,3,'Apocalypse 20:5','Quand les autres morts revivent-ils ?','When do the rest of the dead live again?'),
(18,4,'Jérémie 4:23-26','À quoi ressemble la terre durant ce temps ?','What does the earth look like during that time?'),
(19,1,'Daniel 7:9-10','Quelle scène Daniel contemple-t-il ?','What scene does Daniel behold?'),
(19,2,'Ecclésiaste 12:14','Sur quoi porte le jugement ?','What does the judgment consider?'),
(19,3,'1 Jean 2:1','Qui est notre avocat auprès du Père ?','Who is our advocate with the Father?'),
(19,4,'Apocalypse 14:7','Quel appel accompagne l''heure du jugement ?','What call accompanies the hour of judgment?'),
(20,1,'Apocalypse 12:17','Quels deux traits caractérisent le peuple de Dieu ?','What two traits mark God''s people?'),
(20,2,'Apocalypse 14:12','Que gardent les saints ?','What do the saints keep?'),
(20,3,'Éphésiens 4:4-6','Sur quoi repose l''unité de l''Église ?','On what does the church''s unity rest?'),
(20,4,'Actes 17:11','Quelle attitude les Béréens ont-ils adoptée ?','What attitude did the Bereans adopt?'),
(21,1,'Matthieu 3:13-16','Comment Jésus a-t-il été baptisé ?','How was Jesus baptised?'),
(21,2,'Romains 6:3-4','Que symbolise le baptême ?','What does baptism symbolise?'),
(21,3,'Actes 2:38','Quelles étapes précèdent le baptême ?','What steps precede baptism?'),
(21,4,'Matthieu 28:19-20','Quelle mission Jésus confie-t-il ?','What mission does Jesus entrust?'),
(22,1,'Malachie 3:10','Quelle promesse accompagne la fidélité dans la dîme ?','What promise accompanies faithfulness in tithe?'),
(22,2,'2 Corinthiens 9:7','Dans quel esprit faut-il donner ?','In what spirit should we give?'),
(22,3,'Actes 20:35','Quelle parole de Jésus Paul rappelle-t-il ?','Which saying of Jesus does Paul recall?'),
(22,4,'1 Chroniques 29:14','Quelle est la source de ce que nous offrons ?','What is the source of what we offer?'),
(23,1,'1 Corinthiens 6:19-20','Comment Paul décrit-il le corps du croyant ?','How does Paul describe the believer''s body?'),
(23,2,'1 Corinthiens 10:31','Quel principe guide nos choix quotidiens ?','What principle guides our daily choices?'),
(23,3,'Genèse 1:29','Quel régime alimentaire est présenté au commencement ?','What diet is presented at the beginning?'),
(23,4,'3 Jean 2','Quel souhait Jean exprime-t-il pour son ami ?','What wish does John express for his friend?'),
(24,1,'1 Pierre 2:21','À quoi sommes-nous appelés ?','What are we called to?'),
(24,2,'Jean 13:14-15','Quel exemple Jésus laisse-t-il à ses disciples ?','What example does Jesus leave his disciples?'),
(24,3,'Matthieu 11:28-30','Quelle invitation Jésus adresse-t-il aux fatigués ?','What invitation does Jesus give the weary?'),
(24,4,'Philippiens 1:6','Qui achève l''œuvre commencée en nous ?','Who completes the work begun in us?'),
(25,1,'1 Corinthiens 10:31','Quel principe résume les choix de santé ?','What principle summarises health choices?'),
(25,2,'1 Pierre 2:21','Que signifie suivre les traces de Jésus aujourd''hui ?','What does following Jesus'' footsteps mean today?'),
(25,3,'Josué 24:15','Quelle décision personnelle ce verset propose-t-il ?','What personal decision does this verse propose?'),
(25,4,'Philippiens 4:13','Où trouvons-nous la force de continuer ?','Where do we find the strength to continue?')
) AS v(lpos, qpos, ref, fr, en)
JOIN public.lessons l ON l.position = v.lpos;